name             'sqlserver'
maintainer       'Tomasz Sikora'
maintainer_email 'frakti7@gmail.com'
license          'MIT'
description      'Installs/Configures sqlserver'
long_description 'Installs/Configures sqlserver'
version          '0.2.1'

depends 'sql_server'
depends 'windows_firewall'
